name: Submit a device you have tested
description: Submit your report of a wallet, exchange, or other bitcoin service for compatibility with unified BIP21 QR codes
title: "[Hardware Test]: "
labels: ["hardware-test"]
assignees:
  - sbddesign
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: hardware_name
    attributes:
      label: Hardware Name
      description: The name of the hardware device you tested.
      placeholder: ex. MegaPhone Model X3000
    validations:
      required: true
  - type: input
    id: hardware_uri
    attributes:
      label: Hardware Website
      description: Optionally, the manufacturer's website or link to hardware tech specs.
      placeholder: ex. megaphoneinc.co/x3000/tech-specs.html
  - type: input
    id: wallet_name
    attributes:
      label: App Name
      description: The name of the wallet, exchange, or service provider you used on this piece of hardware
      placeholder: ex. Boss Wallet
    validations:
      required: true
  - type: input
    id: wallet_uri
    attributes:
      label: App Website
      description: The website of the wallet, exchange, or service provider you tested
      placeholder: ex. bosswallet3000.com
  - type: dropdown
    id: scans
    attributes:
      label: Scans BIP-21
      description: Did the wallet successfully scan the BIP21 QR code?
      options:
        - "Yes"
        - "No"
        - "Mixed - it scanned, but with difficulties"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Optional - describe what happened. For example, if your scan results were "mixed", describe your experience.
      placeholder: It scanned eventually, but I had to get the phone at the right angle.